server.port: 8081

spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
      - id: rateLimit_route
        uri: http://localhost:8088/hello
        order: 0
        predicates:
        - Path=/rateLimit/**
        filters:
        #filter名称必须是RequestRateLimiter
        - name: RequestRateLimiter
          args:
            rate-limiter: "#{@systemRedisRateLimiter}"
            key-resolver: "#{@sysKeyResolver}"
#            #使用SpEL按名称引用bean
#            key-resolver: "#{@remoteAddrKeyResolver}"
#            #允许用户每秒处理多少个请求
#            redis-rate-limiter.replenishRate: 1
#            #令牌桶的容量，允许在一秒钟内完成的最大请求数
#            redis-rate-limiter.burstCapacity: 5
#            deny-empty-Key: false
ratelimiter-conf:
  #配置限流参数与RateLimiterConf类映射
  rateLimitMap:
    #格式为：routeid(gateway配置固定).token+path.replenishRate(流速)/burstCapacity令牌桶大小
    rateLimit_route.t1.rateLimit-hello.replenishRate: 1
    rateLimit_route.t1.rateLimit-hello.burstCapacity: 5

logging:
  level:
    #org.springframework.cloud.gateway: debug
    com.batman.gateway: debug